services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - wearables
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s
  api:
    build: ./server/
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s
    networks:
      - wearables
  frontend:
    build: ./client/
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - wearables
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s
    env_file:
      - ./client/.env
  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"
    networks:
      - wearables
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand('ping').ok' | mongosh test --quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
networks:
  wearables:
    name: wearables
    external: true
