services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - wearables
  api:
    build: ./server/
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    depends_on:
      - redis
      - mongo
    restart: unless-stopped
    networks:
      - wearables
  frontend:
    build: ./client/
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - wearables
    env_file:
      - ./client/.env
  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"
    networks:
      - wearables
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
networks:
  wearables:
    name: wearables
    external: true
